version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
  pre_build:
    commands:
      - gem install rspec
      - gem install rspec_junit_formatter
  build:
    commands:
      - rspec spec/TestSearchProduct_spec.rb --format RspecJunitFormatter --out test_report/report
reports:
  rspec_reports:
    files:
      - report
    base-directory: test_report/
    file-format: JUNITXML